/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e8e8e8",
        "tertiary": "#4f5d72",
        "tertiary-fixed": "#d5e3fc",
        "on-tertiary-fixed-variant": "#3a485c",
        "on-background": "#1a1c1c",
        "on-surface": "#1a1c1c",
        "outline": "#717786",
        "primary-container": "#0073df",
        "primary": "#005bb3",
        "tertiary-fixed-dim": "#b9c7e0",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "surface-variant": "#e2e2e2",
        "on-tertiary-fixed": "#0d1c2e",
        "inverse-on-surface": "#f0f1f1",
        "surface-container-highest": "#e2e2e2",
        "primary-fixed-dim": "#a9c7ff",
        "on-tertiary-container": "#fdfcff",
        "surface-container": "#eeeeee",
        "inverse-primary": "#a9c7ff",
        "surface-tint": "#005db7",
        "on-secondary-container": "#606368",
        "primary-fixed": "#d6e3ff",
        "on-error": "#ffffff",
        "secondary": "#5c5e63",
        "surface-container-lowest": "#ffffff",
        "surface": "#f9f9f9",
        "on-primary-fixed-variant": "#00468c",
        "secondary-container": "#dedfe5",
        "surface-dim": "#dadada",
        "on-secondary-fixed": "#191c20",
        "on-primary-container": "#fefcff",
        "on-secondary-fixed-variant": "#44474c",
        "inverse-surface": "#2f3131",
        "secondary-fixed": "#e1e2e8",
        "on-primary": "#ffffff",
        "surface-bright": "#f9f9f9",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#c5c6cc",
        "error": "#ba1a1a",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#001b3d",
        "tertiary-container": "#67758b",
        "outline-variant": "#c0c6d6",
        "surface-container-low": "#f3f3f4",
        "on-surface-variant": "#414754",
        "background": "#f9f9f9"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "stack-lg": "48px",
        "stack-sm": "12px",
        "margin-desktop": "64px",
        "stack-md": "24px",
        "gutter": "24px",
        "container-max": "1280px",
        "section-gap": "120px",
        "unit": "8px",
        "margin-mobile": "20px"
      },
      fontFamily: {
        "display": ["Manrope", "sans-serif"],
        "h3": ["Manrope", "sans-serif"],
        "label-caps": ["Manrope", "sans-serif"],
        "h2": ["Manrope", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "h1": ["Manrope", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "button": ["Manrope", "sans-serif"],
        "manrope": ["Manrope", "sans-serif"]
      },
      fontSize: {
        "display": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "800" }],
        "h3": ["24px", { "lineHeight": "1.4", "fontWeight": "700" }],
        "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "700" }],
        "h2": ["32px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "h1": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "button": ["16px", { "lineHeight": "1", "letterSpacing": "0.02em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
